from django.conf.urls import patterns, include, url
from sklcc import views, tests, forms, pad, chart, measure, utilitys
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url( r'^warning/', views.warning ),
    url( r'^base/',views.base ),
    url( r'^$', views.login ),
    url( r'^login/', views.login ),
    url( r'^logout/$', views.logout ),
    url( r'^submit_id', views.submit_id ),
    url( r'^url_dataentry/$', views.url_dataentry ),
    url( r'^number_off/', views.number_off ),

    url( r'^update_info/', views.update_info ),
    url( r'^commit_res/$', views.commit_res ),

    url( r'^choose/$', views.choose ),
    url( r'^table/$', views.tables ),
    url( r'^commit_table/$', views.commit_table ),
    url( r'^update_table/', views.update_table ),
    url( r'^get_employee/', views.get_employee ),
	url( r'^partition_set/$', views.partion_set ),
	url( r'^submit_partition_set/$', views.submit_partion_set ),
	url( r'^delete_partition_set/$', views.delete_partion_set ),
	url( r'^submit_size_set/$', views.submit_size_set ),

    url( r'^save_table/', views.save_table ),
    url( r'^delete_table', views.delete_record ),
    url( r'^choose_check/$', views.choose_check ),
    url( r'^check/', views.tables_check ),
    url( r'^update_table_check', views.update_table_check ),
    url( r'^pass_table', views.pass_table ),
    url( r'^read_only_table', views.table_read_only ),

    url( r'^line_chart/$', views.line_chart ),
    url( r'^update_line_chart_dept/', views.update_line_chart_dept ),
    url( r'^update_line_chart_batch', views.update_line_chart_batch ),
    url( r'^update_line_chart', views.update_line_chart ),
	url( r'^bar_question_chart/', chart.bar_question_chart ),
	url( r'^pie_chart/$', chart.pie_chart ),
    url( r'^bar_measure_chart/$', chart.bar_measure_chart ),

	url( r'^recheck/$', views.recheck ),
	url( r'^flush_buttons_recheck', views.flush_buttons_recheck ),
	url( r'^get_partition_table', views.get_partition_table ),
    url( r'^recheck_update_batch_and_inspector', views.recheck_update_batch_and_inspector ),
    url( r'^commit_res_recheck/$', views.commit_res_recheck ),
    url( r'^commit_bald_recheck/$', views.commit_bald_recheck ),
    url( r'^choose_recheck/$', views.choose_recheck ),
    url( r'^delete_recheck_table/', views.delete_recheck_table ),
    url( r'^delete_recheck_content/',views.delete_recheck_content ),
    url( r'^save_recheck_table/', views.save_recheck_table ),
    url( r'^recheck_table/', views.recheck_table ),
    url( r'^recheck_check_table/', views.recheck_check_table ),
    url( r'^recheck_read_only_table/', views.recheck_read_only_table ),
    url( r'^update_recheck_info/', views.update_recheck_info ),
    url( r'^commit_gather_recheck_table/', views.update_recheck_state ),
    url( r'^pass_gather_recheck_table/', views.pass_gather_recheck_table ),
    url( r'^pass_recheck_table/', views.pass_recheck_table ),
    url( r'^pass_selected_recheck_table/$', views.pass_selected_recheck_table ),
    url( r'^choose_check_recheck/', views.choose_check_recheck ),

    url( r'^admini/$', views.management ),
    url( r'^add_employee', views.add_employee ),
    url( r'^change_employee', views.change_employee ),
    url( r'^add_department', views.add_department ),
    url( r'^add_authority', views.add_authority ),
    url( r'^change_authority', views.change_authority ),
    url( r'^add_rule/', views.add_employeeno_type ),
    url( r'^change_department', views.change_department ),
    url( r'^change_config', views.change_config ),
    url( r'^change_check_type/', views.change_check_type ),
    url( r'^admin/', include(admin.site.urls)),

    url( r'^form0/$', forms.form_have_submitted ),
	url( r'^update_table_history/', forms.update_table_history ),
	url( r'^update_recheck_table_history/', forms.update_recheck_table_history ),
    url( r'^form1/', forms.quality_check ),
    url( r'^form2/', forms.return_check_percentage ),
    url( r'^form2_bonus',forms.form2_bonus ),
    url( r'^form2_config', forms.form2_config ),
    url( r'^form2_change_config/$', forms.form2_change_config ),
    url( r'^form2_delete_type_name', forms.delete_type_name ),
    url( r'^form3/', forms.total_strong_question ),
    url( r'^form4/', forms.stage_repair ),
    url( r'^form5/', forms.baldric_information ),
    url( r'^form6/', forms.prize_punish ),
    url( r'^form7/', forms.recheck_quality_check ),
    url( r'^update_recheck_efficent/$', forms.update_recheck_efficent ),
    url( r'^form8', forms.factory_num ),
    url( r'^form9', forms.form_return_check ),
    url( r'^form10', forms.effciency_recheck ),
    url( r'^form11', forms.recheckor_total_strong_problem ),
    url( r'^form12', forms.return_percentage_by_batch ),
    url( r'^form13', forms.table_measure_size_in ),
    url( r'^flush_batch', forms.flush_batch ),
	url( r'^myinfo/', views.myinfo ),
	url( r'^myinfo_history/', views.myinfo_history ),
	url( r'^history_table/', views.history_table ),
    url( r'^change_recheck_departmentno_sequence', views.change_recheck_departmentno_sequence ),
    url( r'^myinfo_change_password/', views.change_password ),
    url( r'^add_return_check', views.add_return_check ),
    url( r'^return_check/', views.return_check ),
    url( r'^pass_return_check/', views.pass_return_check ),
    url( r'^return_check_check/', views.return_check_check ),
    url( r'^recheck_return_check/', views.recheck_return_check ),
    url( r'^recheck_return_check_check/', views.recheck_return_check_check ),

	url( r'^pad_login/$', pad.pad_login ),
	url( r'^pad_form_1$', pad.pad_form_1 ),
    url( r'^pad_form_2$', pad.pad_form_2 ),
    url( r'^pad_form_3$', pad.pad_form_3 ),
    url( r'^pad_form_4$', pad.pad_form_4 ),
    url( r'^pad_form_5$', pad.pad_form_5 ),
    url( r'^pad_form_6$', pad.pad_form_6 ),
    url( r'^pad_form_7$', pad.pad_form_7 ),
    url( r'^pad_form_8$', pad.pad_form_8 ),
    url( r'^pad_form_9',  pad.pad_form_9 ),
    url( r'^pad_form_10', pad.pad_form_10 ),
    url( r'^pad_form_11', pad.pad_form_11 ),
    url( r'^pad_form_12', pad.pad_form_12 ),
    url( r'^pad_choose/$', pad.pad_choose ),
    url( r'^pad_choose_check/', pad.pad_choose_check ),
    url( r'^pad_update_table/', pad.pad_update_table ),
	url( r'^pad_choose_recheck/$', pad.pad_choose_recheck ),
    url( r'^pad_choose_recheck_check/', pad.pad_choose_recheck_check ),
    url( r'^pad_update_recheck_table/', pad.pad_update_recheck_table ),

	url( r'^dark_cave_login/$', chart.dark_cave_login ),
    url( r'^hole_login/$', chart.hole_login ),
	url( r'^dark_cave/', chart.dark_cave ),

    url( r'^measure_in/$', measure.measure_in ),
    url( r'^measure_force/$', measure.measure_force ),
    url( r'^measure_force_recheck/$', measure.measure_force_recheck ),
    url( r'^measure_commit/$', measure.measure_commit  ),
    url( r'^measure_check/$', measure.measure_check ),
    url( r'^measure_check_recheck/$', measure.measure_check_recheck ),
    url( r'^measure_check_info/$', measure.measure_check_info ),
    url( r'^get_batch_by_departmentno_and_date', measure.get_batch_by_departmentno_and_date ),
    url( r'^measure_check_pass', measure.measure_check_pass ),
	url( r'^style_measure/$', views.style_measure ),
    url( r'^submit_style_measure/$', views.submit_style_measure ),
    url( r'^style_measure_check/$', measure.style_measure_check ),
    url( r'^commit_style_measure/$', measure.commit_style_measure ),
    url( r'^pass_style_measure/$' , measure.pass_style_measure ),



    url( r'^(500)/$', views.fail ),
    url( r'^(404)/$', views.fail ),
    url( r'^test/$', utilitys.test ),

)
